### PR TITLE
Update to 6.26 OASys assessment

### PR DESCRIPTION
**Pull request by jezhiggins**
* Regenerate the assessments for the new OASys release
* Move assessment sql back into the migration so it gets deployed out normally

If you step through the commits, you can see the question diffs reasonably clearly. There's not a huge change, which makes me feel like this PR is doing the right thing :)

### CODE REVIEW

**Comment by jezhiggins** [comment]
Suggest we don't merge this until after this Friday's show and tell.

**Review by LucasCairns — APPROVED** [review]
LGTM 👍 - sensible to split things back out from a maintenance point of view

**Comment by SWhitlam** [comment]
The only problem with moving back to the migrations is it reintroduces the problem of needing to drop the schema every time the questions change

**Comment by jezhiggins** [comment]
Ok, that's fair but I did want to separate them out from the test data because they are a deployable thing. Would you be happier if they were in a directory of their own? So, not a migration, but also not scratch test data?

**Comment by SWhitlam** [comment]
> Ok, that's fair but I did want to separate them out from the test data because they are a deployable thing. Would you be happier if they were in a directory of their own? So, not a migration, but also not scratch test data?

Is it possible to do that and recreate the data? The issue is the migration fails because these files have a different checksum in Flyway. What we really want is to recreate the data I think if it's changed?

**Comment by jezhiggins** [comment]
We've got two things we're trying to manage I guess - the schema and then our own production data. Let me do some homework.

**Pull request merged**
